Repository DO-NOTTO-DO/NotToDo-AOS, pull requests merged in 2023-01, with the labels that each got.

#14 Feature/4 home bottom navi
  app/src/main/java/kr/co/nottodo/presentation/MainActivity.kt
  app/src/main/res/drawable/menu_achieve_selector.xml
  app/src/main/res/drawable/menu_home_selector.xml
  app/src/main/res/drawable/menu_profile_selector.xml
  app/src/main/res/drawable/menu_recommend_selector.xml
  app/src/main/res/drawable/menu_text_color_selector.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
  app/src/main/res/values/themes.xml
Labels: 윤정🐮

#11 Feature/6 캘린더 바텀시트 캘린더 추가 전까지 제작 완료
  app/src/main/java/kr/co/nottodo/presentation/schedule/bottomsheet/view/CalendarBottomSheet.kt
  app/src/main/res/drawable/rectangle_radius_100.xml
  app/src/main/res/layout/fragment_calendar_bottom_sheet.xml
  app/src/main/res/values/themes.xml
Labels: enhancement, 준서🐯

#15 Feature/13 낫투두 생성 뷰
  app/src/main/java/kr/co/nottodo/presentation/MainActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/view/AdditionActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/viewmodel/AdditionViewModel.kt
  app/src/main/res/drawable/rectangle_border_gray2_1.xml
  app/src/main/res/drawable/rectangle_border_gray4_0point5.xml
  app/src/main/res/drawable/rectangle_border_gray4_1.xml
  app/src/main/res/drawable/rectangle_border_gray_0point5_radius_5.xml
  app/src/main/res/layout/activity_addition.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
Labels: enhancement, 준서🐯

#20 Feature/5 home layout
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/nottodo/HomeFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/MainActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/view/AdditionActivity.kt
  app/src/main/res/drawable/ic_add_notodo_plus.xml
  app/src/main/res/drawable/ic_home_checkbox.xml
  app/src/main/res/drawable/ic_img_home_heart.xml
  app/src/main/res/drawable/rectangle_border_gray2_05.xml
  app/src/main/res/drawable/rectangle_border_gray2_bg_yellow_radius_05.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_blank.xml
  app/src/main/res/layout/item_home_inner.xml
  app/src/main/res/layout/item_home_out.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
Labels: 윤정🐮

#26 Feature/25 search and addition view update
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/view/AdditionActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/viewmodel/AdditionViewModel.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/search/adapter/SearchRecyclerViewAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/search/view/SearchActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/search/viewmodel/SearchViewModel.kt
  app/src/main/res/drawable/ic_btn_plus.xml
  app/src/main/res/drawable/ic_btn_plus_disabled.xml
  app/src/main/res/drawable/ic_btn_plus_enabled.xml
  app/src/main/res/layout/activity_addition.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_search_rv.xml
Labels: enhancement, 준서🐯

#36 [FIX]#34 성취뷰 뷰페이저 크기에 관한 버그
  app/src/main/java/kr/co/nottodo/presentation/achievement/view/AchievementFragment.kt
Labels: enhancement, 준서🐯

#35 [fix]#30 변수 추가하여 상황명이 "입력하기" 여도 추가하기 버튼 활성화되도록 수정
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/view/AdditionActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/viewmodel/AdditionViewModel.kt
Labels: enhancement, 준서🐯

#28 Feature/27 apifactory
  app/src/main/java/kr/co/nottodo/data/remote/api/ApiFactory.kt
  app/src/main/java/kr/co/nottodo/data/remote/api/TokenInterceptor.kt
  app/src/main/java/kr/co/nottodo/data/remote/model/Test.kt
Labels: enhancement, 준서🐯

#33 [UI]#32 하단 여백 수정(92dp->46dp)
  app/src/main/res/layout/fragment_achievement.xml
Labels: enhancement, 준서🐯

#37 Feature/29 search server connection
  app/build.gradle
  app/src/main/java/kr/co/nottodo/data/remote/api/ApiFactory.kt
  app/src/main/java/kr/co/nottodo/data/remote/api/SearchService.kt
  app/src/main/java/kr/co/nottodo/data/remote/model/HistoryDto.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/search/adapter/SearchRecyclerViewAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/search/view/SearchActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/search/viewmodel/SearchViewModel.kt
Labels: enhancement, 준서🐯

#43 Feature/38 statistic server connection
  app/build.gradle
  app/src/main/java/kr/co/nottodo/data/remote/api/ApiFactory.kt
  app/src/main/java/kr/co/nottodo/data/remote/api/StatisticService.kt
  app/src/main/java/kr/co/nottodo/data/remote/api/TokenInterceptor.kt
  app/src/main/java/kr/co/nottodo/data/remote/model/StatisticDto.kt
  app/src/main/java/kr/co/nottodo/presentation/achievement/adapter/AchievementMissionAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/achievement/adapter/AchievementSituationChildAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/achievement/adapter/AchievementSituationParentAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/achievement/adapter/AchievementViewPagerAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/achievement/view/AchievementFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/achievement/viewmodel/AchievementViewModel.kt
  app/src/main/res/layout/activity_addition.xml
Labels: enhancement, 준서🐯

#45 Feature/44 mission post server connection
  app/src/main/java/kr/co/nottodo/data/remote/api/ApiFactory.kt
  app/src/main/java/kr/co/nottodo/data/remote/api/MissionService.kt
  app/src/main/java/kr/co/nottodo/data/remote/model/MissionDto.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/view/AdditionActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/viewmodel/AdditionViewModel.kt
Labels: enhancement, 준서🐯

#50 Feature/48 add calendar
  app/src/main/java/kr/co/nottodo/presentation/achievement/view/AchievementFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/view/AdditionActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/viewmodel/AdditionViewModel.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/bottomsheet/view/CalendarBottomSheet.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/search/view/SearchActivity.kt
  app/src/main/java/kr/co/nottodo/view/calendar/monthly/monthlycalendarpicker/MonthlyCalendarPicker.kt
  app/src/main/res/drawable/rectangle_solid_black_radius_100.xml
  app/src/main/res/drawable/rectangle_solid_gray_radius_100.xml
  app/src/main/res/layout/activity_addition.xml
  app/src/main/res/layout/fragment_achievement.xml
  app/src/main/res/layout/fragment_calendar_bottom_sheet.xml
Labels: enhancement, 준서🐯

#55 Feature/51 achievement calendar server
  app/src/main/java/kr/co/nottodo/data/remote/api/AchievementService.kt
  app/src/main/java/kr/co/nottodo/data/remote/api/ApiFactory.kt
  app/src/main/java/kr/co/nottodo/data/remote/model/AchievementDto.kt
  app/src/main/java/kr/co/nottodo/presentation/achievement/view/AchievementFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/achievement/viewmodel/AchievementViewModel.kt
  app/src/main/java/kr/co/nottodo/view/calendar/monthly/monthlycalendar/MonthlyCalendar.kt
  app/src/main/java/kr/co/nottodo/view/calendar/monthly/util/CalendarUtil.kt
  app/src/main/res/layout/fragment_achievement.xml
Labels: enhancement, 준서🐯

#57 Feature/56 situation statistics UI update
  app/src/main/java/kr/co/nottodo/presentation/achievement/adapter/AchievementSituationParentAdapter.kt
  app/src/main/res/drawable/ic_toggle_closed.xml
  app/src/main/res/drawable/ic_toggle_open.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_achievement_rv_situation_parent.xml
Labels: enhancement, 준서🐯

#59 Feature/41 on board
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/nottodo/presentation/onboard/adapter/OnBoardViewPagerAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/onboard/view/OnBoardBodyActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/onboard/view/OnBoardHeaderActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/onboard/view/fragment/OnBoardFifthFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/onboard/view/fragment/OnBoardFourthFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/onboard/view/fragment/OnBoardSecondFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/onboard/view/fragment/OnBoardThirdFragment.kt
  app/src/main/res/drawable/ic_arrow_left_onboard.xml
  app/src/main/res/drawable/ic_arrow_right_onboard.xml
  app/src/main/res/drawable/ic_onboarding_logo.xml
  app/src/main/res/drawable/ic_onboarding_page1.xml
  app/src/main/res/drawable/ic_onboarding_page2.xml
  app/src/main/res/drawable/ic_onboarding_page3.xml
  app/src/main/res/drawable/ic_onboarding_page4.xml
  app/src/main/res/drawable/ic_onboarding_page5.xml
  app/src/main/res/drawable/ic_prgressbar_first.xml
  app/src/main/res/drawable/ic_progeressbar_second.xml
  app/src/main/res/drawable/ic_progressbar_third.xml
  app/src/main/res/layout/activity_on_board_body.xml
  app/src/main/res/layout/activity_on_board_header.xml
  app/src/main/res/layout/fragment_on_board_fifth.xml
  app/src/main/res/layout/fragment_on_board_fourth.xml
  app/src/main/res/layout/fragment_on_board_second.xml
  app/src/main/res/layout/fragment_on_board_third.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/typography.xml
Labels: enhancement, 준서🐯

#62 Feature/61 code diet
  app/src/main/java/kr/co/nottodo/data/Test.kt
  app/src/main/java/kr/co/nottodo/data/local/Test.kt
  app/src/main/java/kr/co/nottodo/presentation/achievement/adapter/AchievementSituationChildAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/achievement/adapter/AchievementViewPagerAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/achievement/view/AchievementFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/onboard/view/OnBoardBodyActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/onboard/view/fragment/OnBoardFifthFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/onboard/view/fragment/OnBoardFourthFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/onboard/view/fragment/OnBoardThirdFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/adapter/AdditionDropdownHeaderAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/adapter/AdditionDropdownRecentSearchAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/view/AdditionActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/view/AdditionDropdownFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/viewmodel/AdditionViewModel.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/bottomsheet/view/CalendarBottomSheet.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/search/adapter/SearchRecyclerViewAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/search/view/SearchActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/search/viewmodel/SearchViewModel.kt
  app/src/main/java/kr/co/nottodo/util/extension/Test.java
  app/src/main/res/layout/activity_addition.xml
  app/src/main/res/layout/activity_on_board_body.xml
  app/src/main/res/layout/activity_on_board_header.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/fragment_achievement.xml
  app/src/main/res/layout/fragment_addition_dropdown.xml
  app/src/main/res/layout/fragment_calendar_bottom_sheet.xml
  app/src/main/res/layout/fragment_on_board_fifth.xml
  app/src/main/res/layout/fragment_on_board_fourth.xml
  app/src/main/res/layout/fragment_on_board_second.xml
  app/src/main/res/layout/fragment_on_board_third.xml
  app/src/main/res/layout/item_achievement_pager_empty.xml
  app/src/main/res/layout/item_achievement_pager_mission.xml
  app/src/main/res/layout/item_achievement_pager_situation.xml
  app/src/main/res/layout/item_addition_dropdown_header.xml
  app/src/main/res/layout/item_addition_dropdown_recent_search.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, 준서🐯

#58 Feature/52 recommendation server connection
  app/src/main/java/kr/co/nottodo/data/remote/api/ApiFactory.kt
  app/src/main/java/kr/co/nottodo/data/remote/api/ResponseRecommendationCategoryListService.kt
  app/src/main/java/kr/co/nottodo/data/remote/api/ResponseRecommendationCategorySituationService.kt
  app/src/main/java/kr/co/nottodo/presentation/MainActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/data/recommendationlistdata/RecommendationChildData.kt
  app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/data/responsedto/ResponseAddSituationDto.kt
  app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/data/responsedto/ResponseBase.kt
  app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/data/responsedto/ResponseRecommendationCategoryListDto.kt
  app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/data/responsedto/ResponseRecommendationCategorySituationDto.kt
  app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/recommendationfragment/RecommendationAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/recommendationfragment/RecommendationFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/recommendationfragment/RecommendationViewHolder.kt
  app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/recommendationlist/RecommendationChildAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/recommendationlist/RecommendationChildViewHolder.kt
  app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/recommendationlist/RecommendationParentAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/recommendationlist/RecommendationParentViewHolder.kt
  app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/viewmodel/RecommendationViewModel.kt
  app/src/main/res/drawable/ic_recommendation_circle_yellow.xml
  app/src/main/res/drawable/line_bottom_gray2_0point5.xml
  app/src/main/res/drawable/rectangle_recommendation_list_title.xml
  app/src/main/res/drawable/rectangle_recommendation_list_yellow.xml
  app/src/main/res/layout/fragment_recommendation.xml
  app/src/main/res/layout/item_nottodo_recommendation_list.xml
  app/src/main/res/layout/item_nottodo_recommendation_list_title.xml
  app/src/main/res/layout/item_recommend.xml
Labels: 민영🐰

#66 Feature/63 낫투두 추가 뷰 - 추천받기, 상황추가 뷰 연결 중간 PR
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/nottodo/presentation/addsituation/AddSituationActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/view/AdditionActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/search/view/SearchActivity.kt
  app/src/main/res/anim/animation_enter.xml
  app/src/main/res/anim/animation_exit.xml
  app/src/main/res/layout/activity_add_situation.xml
  app/src/main/res/layout/activity_addition.xml
Labels: enhancement, 준서🐯

#67 Feature/53 add situation server connect
  app/src/main/java/kr/co/nottodo/data/remote/api/AddSituationService.kt
  app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/viewmodel/AddSituationViewModel.kt
Labels: 민영🐰

#73 Feature/70 add situation server
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/nottodo/data/remote/api/AddSituationService.kt
  app/src/main/java/kr/co/nottodo/data/remote/api/ApiFactory.kt
  app/src/main/java/kr/co/nottodo/data/remote/model/AddSituationDto.kt
  app/src/main/java/kr/co/nottodo/presentation/addsituation/AddSituationActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/addsituation/view/AddSituationActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/addsituation/viewmodel/AddSituationViewModel.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/view/AdditionActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/recommendationfragment/RecommendationFragment.kt
  app/src/main/java/kr/co/nottodo/util/extension/FlexboxExtension.kt
  app/src/main/res/layout/activity_add_situation.xml
Labels: enhancement, 준서🐯

#75 Feature/74 toast custom
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/view/AdditionActivity.kt
  app/src/main/java/kr/co/nottodo/view/snackbar/CustomSnackBar.kt
  app/src/main/res/drawable/ic_warning.xml
  app/src/main/res/layout/view_snack_bar.xml
  app/src/main/res/values/colors.xml
Labels: enhancement, 준서🐯

#84 Feature/77 error fix
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/nottodo/Application.kt
  app/src/main/java/kr/co/nottodo/data/remote/api/MissionService.kt
  app/src/main/java/kr/co/nottodo/presentation/MainActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/addsituation/view/AddSituationActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/home/HomeFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/view/AdditionActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/viewmodel/AdditionViewModel.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/bottomsheet/view/CalendarBottomSheet.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/search/view/SearchActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/recommendationfragment/RecommendationFragment.kt
  app/src/main/java/kr/co/nottodo/util/extension/KeyBoardUtil.kt
  app/src/main/res/layout/activity_add_situation.xml
  app/src/main/res/layout/activity_addition.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/fragment_home.xml
Labels: bug, 준서🐯

#89 Feature/88 after plan qa
  app/src/main/java/kr/co/nottodo/presentation/achievement/adapter/AchievementMissionAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/achievement/adapter/AchievementSituationChildAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/achievement/adapter/AchievementSituationParentAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/addsituation/view/AddSituationActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/view/AdditionActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/addition/viewmodel/AdditionViewModel.kt
  app/src/main/java/kr/co/nottodo/presentation/schedule/search/view/SearchActivity.kt
  app/src/main/java/kr/co/nottodo/view/snackbar/CustomSnackBar.kt
  app/src/main/res/drawable/ic_notodo_rang_bg_third.xml
  app/src/main/res/drawable/ic_rank_toggleoff_first.xml
  app/src/main/res/drawable/ic_rank_toggleon_first.xml
  app/src/main/res/drawable/rectangle_no_bottom_gray2_0point5.xml
  app/src/main/res/drawable/rectangle_recommendation_list_title.xml
  app/src/main/res/drawable/rectangle_recommendation_list_yellow.xml
  app/src/main/res/drawable/rectangle_solid_yellow.xml
  app/src/main/res/layout/activity_add_situation.xml
  app/src/main/res/layout/activity_addition.xml
  app/src/main/res/layout/activity_recommendation.xml
  app/src/main/res/layout/fragment_achievement.xml
  app/src/main/res/layout/fragment_recommendation.xml
  app/src/main/res/layout/item_achievement_rv_situation_parent.xml
  app/src/main/res/layout/item_nottodo_recommendation_list.xml
  app/src/main/res/layout/item_nottodo_recommendation_list_title.xml
  app/src/main/res/layout/item_recommend.xml
  app/src/main/res/layout/view_snack_bar.xml
Labels: enhancement, 준서🐯

#91 Feature/81 xml string
  app/src/main/res/layout/activity_add_situation.xml
  app/src/main/res/layout/activity_recommendation.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_recommendation.xml
  app/src/main/res/layout/view_add_situation_list_text.xml
  app/src/main/res/layout/view_add_situaution_recent_list_text.xml
  app/src/main/res/layout/view_calendar_week_description.xml
  app/src/main/res/values/strings.xml
Labels: 민영🐰

#97 Feature/90 design qa
  app/src/main/java/kr/co/nottodo/presentation/achievement/view/AchievementFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/home/HomeFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/mypage/view/MyPageFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/onboard/view/OnBoardBodyActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/onboard/view/OnBoardHeaderActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/recommendationactivity/RecommendationActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/recommendationfragment/RecommendationFragment.kt
  app/src/main/java/kr/co/nottodo/util/extension/ActivityExtension.kt
  app/src/main/res/anim/animation_enter.xml
  app/src/main/res/anim/animation_exit.xml
  app/src/main/res/layout/activity_add_situation.xml
  app/src/main/res/layout/activity_addition.xml
  app/src/main/res/layout/activity_recommendation.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/fragment_recommendation.xml
  app/src/main/res/layout/item_achievement_rv_mission.xml
  app/src/main/res/layout/item_achievement_rv_situation_child.xml
  app/src/main/res/layout/item_achievement_rv_situation_parent.xml
  app/src/main/res/layout/view_snack_bar.xml
  app/src/main/res/values/themes.xml
Labels: enhancement, 준서🐯
